import { Header } from "./header";
import { Footer } from "./footer";
import "@/styles/globals.css";
import ChakraProvider from "@client-packages/chakra-ui/chackraProvider";
import theme from "../config/theme";
import Fonts from "../config/fonts";
import { CountryNamespace } from "@/types/country";
import { API_ROUTES } from "@/routes";


export const metadata = {
  title: 'وبسایت کوچا',
  description: 'Generated by Next.js',
  viewport: "width=device-width, initial-scale=1",
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  let countries: CountryNamespace.GET[]
  try{
    countries = await (await API_ROUTES.COUNTRIES.GET_ALL("default", 20)).json()
  }
  catch(e){
    throw new Error("error in get country")
  }

  return (
    <html lang="fa" dir="rtl">
      <body>
      <ChakraProvider theme={theme}>
        <Fonts />
        <Header countries={countries} />
          {children}
        <Footer />
      </ChakraProvider>
      </body>
    </html>
  )
}
