import { Header } from "./header";
import { Footer } from "./footer";
import "@/styles/globals.css";
import ChakraProvider from "./chackraProvider";
import theme from "../config/theme";
import Fonts from "../config/fonts";


export const metadata = {
  title: 'وبسایت کوچا',
  description: 'Generated by Next.js',
  viewport: "width=device-width, initial-scale=1",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fa" dir="rtl">
      <body>
      <ChakraProvider theme={theme}>
        <Fonts />
        <Header />
          {children}
        <Footer />
      </ChakraProvider>
      </body>
    </html>
  )
}
