export const GENERAL = {
  ALL: "همه",
  ALL_COUNTRIES: "همه کشورها",
  HOME: "خانه",
  ALL_IMAGES_VIEW: "مشاهده تمامی تصاویر",
  CONFIRM: "تایید",
  ABOUT: "درباره کـوچـا",
  ADD_LIST: "افزودن کسب و کار",
  BACK_TO_LIST: "بازگشت به لیست",
  CATEGORY: "دسته‌بندی",
  CATEGORY_SELECT: "انتخاب دسته‌بندی",
  CATEGORIES: "دسته‌بندی‌ها",
  ALL_CATEGORIES: "همه دسته‌بندی‌ها",
  COPYRIGHT_TEXT1: "تمامی حقوق ناشی از این وب سایت برای",
  COPYRIGHT_TEXT2: "محفوظ است.",
  ALL_CITIES: "همه شهرها",
  CITY: "شهر",
  CITIES: "شهرها",
  CITY_NAME: "نام‌شهر",
  CITY_SELECT: "انتخاب شهر",
  CONTACT_INFO: "اطلاعات تماس",
  CONTACT_US: "تماس با ما",
  CORPORATE_OPPORTUNITIES: "فرصت‌های همکاری",
  COMMENT_SUBMIT: "ثبت نظر",
  USERS_COMMENTS: "نظرات کاربران",
  CLOSED: "تعطیل",
  DESCRIPTION: "توضیحات",
  EMAIL: "ایمیل",
  FACILITIES: "امکانات",
  FILTERS: "فیلترها",
  FILTER_APPLY: "اعمال فیلترها",
  FILTER_SELECT_PLEASE: "لطفا فیلترهای خود را انتخاب کنید",
  FEATURED: "ویژه",
  IMAGES: "تصاویر",
  ITEM: "مورد",
  IS_OPEN: "باز است",
  KOOCHAA: "کوچا",
  KOOCHAA_SLOGAN: "جامعه پارسی زبانان مهاجر",
  LIST: "جستجوی مشاغل",
  LOGIN_REGISTER: "ورود | ثبت نام",
  MOBILE: "تلفن همراه",
  NEW: "جدید",
  PHONE: "تلفن ثابت",
  REPORT_PAGE: "گزارش صفحه",
  SOCIAL_MEDIA: "رسانه‌های اجتماعی",
  SELECT: "انتخاب کنید",
  PLEASE_SELECT: "لطفا انتخاب کنید",
  SHARING: "اشتراک گذاری",
  TIMES: "بار",
  TOOLS: "ابزارها",
  VIEW: "بازدید",
  WEBSITE: "وب سایت",
  WORKING_HOURS: "ساعات کاری",
  TERMS_AND_CONDITIONS: "قوانین و مقررات",
};
export const SOCIAL = {
  FACEBOOK: "فیس بوک",
  INSTAGRAM: "اینستاگرام",
  YOUTUBE: "یوتیوب",
  LINKEDIN: "لینکدین",
};
export const CATEGORY = {
  RESTAURANT: "رستوران",
  SUPERMARKET: "سوپر مارکت",
  DRIVING_SCHOOL: "آموزشگاه رانندگی",
  ZANAN: "متخصص زنان‌و‌زایمان",
  GOOSH: "متخصص گوش و حلق و بینی",
};

export const MODAL = {
  COUNTRY_TITLE: "لطفا کشور مورد نظر خود را انتخاب نمایید",
};

export const COUNTRY = {

  GERMANY: "آلمان",
  ENGLAND: "انگلستان",
  SWEDEN: "سوئد",
  AUSTRIA: "اتریش",
  TURKEY: "ترکیه",
  CANADA: "کانادا",
  USA: "آمریکا",
  AUSTRALIA: "استرالیا",
  UAE: "امارات",
  MALAYSIA: "مالزی",
  FRANCE: "فرانسه",
  NETHERLANDS: "هلند",
  ITALY: "ایتالیا",
  DENMARK: "دانمارک",
  BELGIUM: "بلژیک",
  NEWZEALAND: "نیوزلند",
  KUWAIT: "کویت",
  QATAR: "قطر",
  ARMENIA: "ارمنستان",
  SWITZERLAND: "سوئیس",
  NORWAY: "نروژ",
  GEORGIA: "گرجستان",
  SPAIN: "اسپانیا",
  RUSSIA: "روسیه",
  FINLAND: "فنلاند",
  CYPRUS: "قبرس",
  JAPAN: "ژاپن",
};
export const MENU = {
  BUSINESSES: "مشاغل فارسی‌زبان",
  DOCTORS: "پزشکان فارسی‌زبان",
  FREELANCERS: "فریلنسرهای فارسی‌زبان",
  COMMUNITIES: "جوامع فارسی‌زبان",
};
export const DAYS = {
  MONDAY: "دوشنبه",
  TUESDAY: "سه‌شنبه",
  WEDNESDAY: "چهارشنبه",
  TURSDAY: "پنجشنبه",
  FRIDAY: "جمعه",
  SATURDAY: "شنبه",
  SUNDAY: "یکشنبه",
};
