export const GENERAL = {
  ADD_LIST: "افزودن کسب و کار",
  ALL_CATEGORIES: "همه دسته‌بندی‌ها",
  ALL_CITIES: "همه شهرها",
  ALL_IMAGES_VIEW: "مشاهده تمامی تصاویر",
  ALL: "همه",
  BACK_TO_LIST: "بازگشت به لیست",
  CANCELL: "لغو",
  CLOSED: "تعطیل",
  COMMENT_SUBMIT: "ثبت نظر",
  CONFIRM: "تایید",
  CONTACT_INFO: "اطلاعات تماس",
  DELETE_ALL: "حذف همه",
  EMAIL: "ایمیل",
  FEATURED: "ویژه",
  HOME: "خانه",
  IS_OPEN: "باز است",
  KOOCHAA_SLOGAN: "جامعه پارسی زبانان مهاجر",
  KOOCHAA: "کوچا",
  LIST: "جستجوی مشاغل",
  LOGIN_REGISTER: "ورود | ثبت نام",
  MOBILE: "تلفن همراه",
  NEW: "جدید",
  PHONE: "تلفن ثابت",
  PLEASE_SELECT: "لطفا انتخاب کنید",
  REPORT_PAGE: "گزارش صفحه",
  SELECT: "انتخاب کنید",
  SHARING: "اشتراک گذاری",
  SOCIAL_MEDIA: "رسانه‌های اجتماعی",
  TIMES: "بار",
  TOOLS: "ابزارها",
  VIEW: "بازدید",
  WEBSITE: "وب سایت",
  WORKING_HOURS: "ساعات کاری",
  PERSIAN: "فارسی زبان",
  LOADING: "درحال بارگذاری",
};
