export const GENERAL = {
  ADD_LIST: "افزودن کسب و کار",
  ALL: "همه",
  ALL_CATEGORIES: "همه دسته‌بندی‌ها",
  ALL_CITIES: "همه شهرها",
  ALL_IMAGES_VIEW: "مشاهده تمامی تصاویر",
  BACK_TO_LIST: "بازگشت به لیست",
  CANCELL: "لغو",
  CLICK_IT: "کلیک کنید",
  CLOSED: "تعطیل",
  COMMENT_SUBMIT: "ثبت نظر",
  CONFIRM: "تایید",
  CONTACT_INFO: "اطلاعات تماس",
  DELETE_ALL: "حذف همه",
  EMAIL: "ایمیل",
  FEATURED: "ویژه",
  HOME: "خانه",
  HOME_JOB: "شغل خانگی",
  IS_OPEN: "باز است",
  KOOCHAA: "کوچا",
  KOOCHAA_SLOGAN: "جامعه پارسی زبانان مهاجر",
  LIST: "جستجوی مشاغل",
  LOADING: "درحال بارگذاری",
  LOAD_MORE: "مشاهده موارد بیشتر",
  LOGIN_REGISTER: "ورود | ثبت نام",
  MOBILE: "همراه",
  NEW: "جدید",
  NEXT: "بعدی",
  PERSIAN: "فارسی زبان",
  PHONE: "تلفن",
  PHONE_COPIED: "شماره تلفن کپی شد.",
  PLEASE_SELECT: "لطفا انتخاب کنید",
  PREVIOUS: "قبلی",
  REPORT_PAGE: "گزارش صفحه",
  SELECT: "انتخاب کنید",
  SHARING: "اشتراک گذاری",
  SOCIAL_MEDIA: "رسانه‌های اجتماعی",
  TIMES: "بار",
  TO: "تا",
  TODAY: "امروز",
  TOOLS: "ابزارها",
  URL_COPIED: "آدرس این صفحه کپی شد.",
  VIEW: "بازدید",
  WEBSITE: "وب‌سایت",
  WORKING_HOURS: "ساعات کاری",
};